language: node_js
services:
  - 'docker'
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - travis_wait 80 ng build --prod --build-optimizer false
  - docker build -t noahch/blogdiff-web .
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push noahch/blogdiff-web;
    fi
